// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZUNpGIVot0zY6Nj2K5wJsU1koabLFDNU',
    appId: '1:714572107654:web:e2798698d5dcf2fc786607',
    messagingSenderId: '714572107654',
    projectId: 'event-manager-app-123',
    authDomain: 'event-manager-app-123.firebaseapp.com',
    storageBucket: 'event-manager-app-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoJzHLJ_wuI7e4bEjrei6Tmba4sAwnBwY',
    appId: '1:714572107654:android:c474b1f65e740f45786607',
    messagingSenderId: '714572107654',
    projectId: 'event-manager-app-123',
    storageBucket: 'event-manager-app-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_PQ7OSn7x32aUIBfh239yjHzFKqu4wbM',
    appId: '1:714572107654:ios:8f4484008f2d57a7786607',
    messagingSenderId: '714572107654',
    projectId: 'event-manager-app-123',
    storageBucket: 'event-manager-app-123.firebasestorage.app',
    iosBundleId: 'com.example.eventManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_PQ7OSn7x32aUIBfh239yjHzFKqu4wbM',
    appId: '1:714572107654:ios:8f4484008f2d57a7786607',
    messagingSenderId: '714572107654',
    projectId: 'event-manager-app-123',
    storageBucket: 'event-manager-app-123.firebasestorage.app',
    iosBundleId: 'com.example.eventManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZUNpGIVot0zY6Nj2K5wJsU1koabLFDNU',
    appId: '1:714572107654:web:afdc481b7bf233a4786607',
    messagingSenderId: '714572107654',
    projectId: 'event-manager-app-123',
    authDomain: 'event-manager-app-123.firebaseapp.com',
    storageBucket: 'event-manager-app-123.firebasestorage.app',
  );
}
